spring.application.name=Authentication
spring.datasource.url=jdbc:mysql://localhost:3306/Authentication
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=Max
spring.security.user.password=Max123
